site_name: Costa Rica AI Workshop 2025
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  ##- markdown_include.include:
  ##    base_path: .
  - admonition

nav:
  - index.md
  - 1day.md
  - 2day.md
