site_name: Costa Rica AI Workshop 2025

theme:
  name: readthedocs
  highlightjs: true
  #  logo: /imgs/tacc-logo-with-words.svg

#extra_css:
#  - css/extra.css

plugins:
  - search

markdown_extensions:
  - extra
  - admonition
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading


nav:
  - index.md
  - Course Schedule:
    - Schedule: 1day/schedule.md
    - Class Introduction: 1day/intro.md
    - Ecosystem: 1day/ecosystem.md
    - Pandas: 1day/pandas/pandas.md
  - Day 2:
    - 2day/schedule.md
    - 2day/clustering.md
  - Day 3:
    - 3day/schedule.md
  - Day 4:
    - 4day/schedule.md
  - Day 5:
    - 5day/schedule.md



