site_name: Costa Rica AI 2025 Workshop 2025

theme:
  name: readthedocs 
  highlightjs: true


plugins:
  - search

markdown_extensions:
  - extra
  - admonition
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading


nav:
  - index.md

  - Lunes:
    - Welcome to TACC (.pptx download): WelcomeToTACC.pptx
    - Intro to Data Science (.pptx download): IntroDataScience.pptx
    - Intro to Pandas (.pptx download): Pandas.pptx

  - Martes:
    - Notas del Martes: tuesdaynotes.md
    - Intro to Matplotlib (.pptx download): Matplotlib.pptx
    - Feature Engineering (notes): featureengineering.md
    - Feature Engineering (.pptx download): featureengineering.pptx

  - Miercoles:
    - Notas del Miercoles: wednesdaynotes.md
    - Classification (notes): classification.md
    - Clustering (notes): clustering.md
    - Classification and Clustering (.pptx download): ClassificationClustering.pptx
    - Choosing the Right Algorithm: choosing.md

  - Jueves:
    - Recommended Data Set Sizes by Model Type: datasetsizes.md
    - Notes del Jueves: thursdaynotes.md
    - Regression and Forecasting (.pptx download): RegressionForecasting.pptx


  - Hack Time:
    - It's Hack Time: hack.md
