site_name: Costa Rica AI Workshop 2025

theme:
  name: readthedocs
  highlightjs: true
  #  logo: /imgs/tacc-logo-with-words.svg


#extra_css:
#  - css/extra.css


plugins:
  - search


markdown_extensions:
  - extra
  - admonition
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading



nav:
  - index.md
  - 1day.md
  - 2day.md
