site_name: Costa Rica AI 2025 Workshop 2025

theme:
  name: readthedocs 
  highlightjs: true


plugins:
  - search

markdown_extensions:
  - extra
  - admonition
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading


nav:
  - index.md

  - Lunes:
    - Welcome to TACC (.pptx download): WelcomeToTACC.pptx
    - Intro to Data Science (.pptx download): IntroDataScience.pptx
    - Intro to Pandas (.pptx download): Pandas.pptx

  - Martes:
    - Tuesday notes: tuesdaynotes.md
    - Intro to Matplotlib (.pptx download): Matplotlib.pptx
    - Feature Engineering (notes): featureengineering.md
    - Feature Engineering (slides): featureengineering.pptx

  - Miercoles:
    - Classification: classification.md
      


 




