site_name: Costa Rica AI Workshop 2025

theme:
  name: tacc_readthedocs
  highlightjs: true


plugins:
  - search

markdown_extensions:
  - extra
  - admonition
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading


nav:
  - index.md
  - Welcome to TACC: WelcomeToTACC.pptx
  - Intro to Data Science: IntroDataScience.pptx
  - Intro to Pandas: Pandas.pptx
  - Intro to Matplotlib: Matplotlib.pptx

